name: Make a release

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: Test
      run: npm run test

    - name: Build
      run: npm run build

    - name: Compress Artifacts
      run: tar -cvzf apps.tar.gz -C dist .

    - name: Upload binaries to release page
      uses: softprops/action-gh-release@v1
      with:
        files: apps.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
