name: Make a release

on:
    push:
        tags:
            - v*.*.*

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build

            - name: Compress Artifacts
              run: npm pack

            - name: Upload binaries to release page
              uses: softprops/action-gh-release@v1
              with:
                  files: vanellus-0.0.1.tgz
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
