name: Push

on:
  push:
    tags-ignore:
      - "*"
  pull_request:
  workflow_call:

env:
  REGISTRY: ghcr.io

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Start Test Backend
        run: |
          cd test_backend
          docker-compose pull
          docker-compose up -d
          cd ..

      - name: Test
        run: npm run test
