name: Make a release

on:
  release:
    types: [created]

jobs:
    test:
        uses: kiebitz-oss/vanellus-inoeg/.github/workflows/push.yaml@main

    release:
        runs-on: ubuntu-latest
        needs:
            - test

        permissions: 
            contents: read
            packages: write 

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            # Setup .npmrc file to publish to GitHub Packages
            - uses: actions/setup-node@v2
              with:
                node-version: '16.x'
                registry-url: 'https://npm.pkg.github.com'

            - name: Install dependencies
              run: npm ci
              
            - name: Build
              run: npm run build

            - name: Compress Artifacts
              run: npm pack

            - name: Upload binaries to release page
              uses: softprops/action-gh-release@v1
              with:
                  files: "*.tgz"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Push package to registry
              run: npm publish
              env:
                NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
